<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>LoggingProviderService.EFCore</PackageId>
		<Version>1.0.0</Version>
		<Authors>Mohammad Taghizadeh</Authors>
		<Company>Arman Tose'e Narmafzar Iranian</Company>
		<RepositoryUrl>https://github.com/Mo-Taghizadeh</RepositoryUrl>
		<Description>ASP.NET Core Logging Provider for EduFlux.</Description>
		<PackageTags>Logging; EFCore; Middleware; ActionFilter; EduFlux</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />

	</ItemGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Abstractions\LoggingProviderService.Abstractions.csproj" />
	</ItemGroup>
</Project>