<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>LoggingProviderService.EFCore</PackageId>
		<Version>1.0.0</Version>
		<Authors>LoggingProviderService</Authors>
		<Description>EF Core provider for LoggingProviderService.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
	</ItemGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Abstractions\LoggingProviderService.Abstractions.csproj" />
	</ItemGroup>
</Project>